DELETE http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbGwyQGNvZGVtb29yZS5jb20iLCJleHAiOjE3MTE5MzIyNzEsInVzZXJJZCI6Mn0.5GCC9SpSe-qLIkSWfhSDcQ0_zD2jXF5jtgiak9hHrvA